sudo: required
services:
  - docker

before_install:
  # login to dockerhub to fix bug limit pull request
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker build -t sirdnt/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sirdnt/react-test npm test

deploy:
  provider: script
  script: bash docker_hub_push
  on:
    branch: master